/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pattern;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;

public class App extends Object {

    public static void main(String[] args) {
        String fileName = "data1.txt";
        boolean isPending = true;
        while (isPending) {
            try {
                System.out.println("Pending : " + fileName);
                File f = new File(fileName);
                FileReader fr = new FileReader(f);
                BufferedReader br = new BufferedReader(fr);
                System.out.println("Complete : " + br.readLine());
                br.close();
                isPending = false;
            } catch (Exception e) {
                System.out.println(fileName + "을 아직 로드하지 못했어요.");
            }

            // 1초 쉬고 다시 찾기
            try {
                Thread.sleep(1000);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
}
